Repository SOPT-SOPHY/SOPHY-Server, pull requests merged in 2023-10, with the labels that each got.

#92 Refactor/#91 change my sophy booktalk
  src/main/java/org/sophy/sophy/controller/MemberController.java
  src/main/java/org/sophy/sophy/controller/MySophyController.java
  src/main/java/org/sophy/sophy/exception/SuccessStatus.java
  src/main/java/org/sophy/sophy/jwt/TokenProvider.java
  src/main/java/org/sophy/sophy/service/MemberService.java
  src/main/java/org/sophy/sophy/service/MySophyService.java
Labels: 구조 변경

#95 Refactor/#94 register profile
  src/main/java/org/sophy/sophy/controller/MemberController.java
  src/main/java/org/sophy/sophy/domain/Member.java
  src/main/java/org/sophy/sophy/domain/dto/mypage/MyPageDto.java
  src/main/java/org/sophy/sophy/exception/SuccessStatus.java
  src/main/java/org/sophy/sophy/external/client/aws/S3Service.java
  src/main/java/org/sophy/sophy/service/MemberService.java
Labels: 개발

#100 Feat/#96 add isapply
  src/main/java/org/sophy/sophy/controller/BooktalkController.java
  src/main/java/org/sophy/sophy/domain/dto/booktalk/response/BooktalkDetailResponseDto.java
  src/main/java/org/sophy/sophy/exception/ErrorStatus.java
  src/main/java/org/sophy/sophy/service/BooktalkService.java
Labels: 개발

#101 fix: 비회원일 때 북토크 상세조회 가능하도록 수정
  src/main/java/org/sophy/sophy/controller/BooktalkController.java
  src/main/java/org/sophy/sophy/service/BooktalkService.java
Labels: 오류

#103 Modify/#102 get booktalk list
  src/main/java/org/sophy/sophy/controller/BooktalkController.java
  src/main/java/org/sophy/sophy/domain/dto/booktalk/response/BooktalkResponseDto.java
  src/main/java/org/sophy/sophy/infrastructure/query/BooktalkQueryRepository.java
  src/main/java/org/sophy/sophy/service/BooktalkService.java
Labels: 개발

#105 fix: refresh token 일치하지 않을 시 SophyJwtException으로 수정
  src/main/java/org/sophy/sophy/exception/ErrorStatus.java
  src/main/java/org/sophy/sophy/service/common/AuthService.java
Labels: 오류

#110 refactor: 다른 객체 수를 파악하는 의존성 필드 제거
  src/main/java/org/sophy/sophy/domain/AuthorProperty.java
  src/main/java/org/sophy/sophy/domain/Booktalk.java
  src/main/java/org/sophy/sophy/domain/CompletedBooktalk.java
  src/main/java/org/sophy/sophy/domain/Member.java
  src/main/java/org/sophy/sophy/domain/MemberBooktalk.java
  src/main/java/org/sophy/sophy/infrastructure/query/BooktalkQueryRepository.java
  src/main/java/org/sophy/sophy/service/BooktalkService.java
  src/main/java/org/sophy/sophy/service/HomeService.java
Labels: 구조 변경
